# Generated by Django 3.2 on 2022-09-19 06:08

from django.db import migrations, models
import django.db.models.deletion
import uuid
import website.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=128)),
                ('url', models.URLField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Snap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snap', models.ImageField(upload_to=website.models.upload_image_to)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snaps', to='website.website')),
            ],
        ),
    ]
