# Generated by Django 3.2 on 2022-09-19 11:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='snap',
            options={'verbose_name': 'スナップショット', 'verbose_name_plural': 'スナップショット'},
        ),
        migrations.AlterModelOptions(
            name='website',
            options={'verbose_name': 'WEBサイト', 'verbose_name_plural': 'WEBサイト'},
        ),
        migrations.AddField(
            model_name='snap',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='snap',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 9, 19, 11, 21, 2, 437941, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='snap',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='snap',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
