# Generated by Django 3.2 on 2022-09-19 12:39

from django.db import migrations, models
import uuid
import website.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_snap_snap'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('snap', models.ImageField(upload_to=website.models.upload_image_to)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
