# Generated by Django 3.2 on 2022-09-19 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_pic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pic',
        ),
    ]
